version: "3.5"
networks:
  default:
    name: universal-resolver
services:
  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "8080:8080"
  driver-did-jnctn:
    image: jnctn/driver-did-jnctn:latest
    ports:
      - "8029:80"